"""vLLM server config and dynamic LoRA manifest generator.

Generates ready-to-use vLLM launch configs for:
  - Base model serving
  - Dynamic LoRA adapter loading
  - Multi-model serving manifests
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def generate_vllm_config(
    model_path: str,
    adapters: list[dict[str, str]] | None = None,
    tensor_parallel: int = 1,
    gpu_memory_utilization: float = 0.90,
    max_model_len: int = 4096,
    dtype: str = "auto",
    quantization: str | None = None,
    host: str = "0.0.0.0",
    port: int = 8000,
) -> dict[str, Any]:
    """Return a vLLM server config dict.

    Args:
        model_path:             Path or HF ID of the base model.
        adapters:               List of {name, path} dicts for dynamic LoRA.
        tensor_parallel:        Number of GPUs for tensor parallelism.
        gpu_memory_utilization: Fraction of GPU memory to use.
        max_model_len:          Maximum context length.
        dtype:                  Weight dtype ("auto", "float16", "bfloat16").
        quantization:           Optional quantization ("awq", "gptq", "squeezellm").
        host:                   Server bind address.
        port:                   Server port.
    """
    cfg: dict[str, Any] = {
        "model": model_path,
        "host": host,
        "port": port,
        "dtype": dtype,
        "tensor_parallel_size": tensor_parallel,
        "gpu_memory_utilization": gpu_memory_utilization,
        "max_model_len": max_model_len,
        "trust_remote_code": True,
    }

    if quantization:
        cfg["quantization"] = quantization

    if adapters:
        cfg["enable_lora"] = True
        cfg["max_loras"] = len(adapters)
        cfg["lora_modules"] = [
            {"name": a["name"], "path": a["path"]}
            for a in adapters
        ]

    return cfg


def generate_launch_script(config: dict[str, Any]) -> str:
    """Return a shell script that launches vLLM with the given config."""
    model = config["model"]
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by distill.export.vllm_config_generator",
        "set -euo pipefail",
        "",
        "python -m vllm.entrypoints.openai.api_server \\",
        f"    --model {model} \\",
        f"    --host {config['host']} \\",
        f"    --port {config['port']} \\",
        f"    --dtype {config['dtype']} \\",
        f"    --tensor-parallel-size {config['tensor_parallel_size']} \\",
        f"    --gpu-memory-utilization {config['gpu_memory_utilization']} \\",
        f"    --max-model-len {config['max_model_len']} \\",
        f"    --trust-remote-code \\",
    ]
    if config.get("quantization"):
        lines.append(f"    --quantization {config['quantization']} \\")
    if config.get("enable_lora"):
        lines.append("    --enable-lora \\")
        lines.append(f"    --max-loras {config['max_loras']} \\")
        for lora in config.get("lora_modules", []):
            lines.append(f"    --lora-modules {lora['name']}={lora['path']} \\")
    # Remove trailing backslash from last line
    lines[-1] = lines[-1].rstrip(" \\")
    lines.append("")
    return "\n".join(lines)


def generate_docker_compose(config: dict[str, Any], model_name: str) -> str:
    """Return a docker-compose.yml snippet for the vLLM service."""
    model = config["model"]
    port = config["port"]
    return f"""version: "3.9"
services:
  {model_name}-vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - {model}:/model:ro
    command: >
      --model /model
      --host 0.0.0.0
      --port {port}
      --dtype {config['dtype']}
      --max-model-len {config['max_model_len']}
    ports:
      - "{port}:{port}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: {config['tensor_parallel_size']}
              capabilities: [gpu]
"""


def save_config(config: dict[str, Any], output_dir: str) -> dict[str, str]:
    """Write vllm_config.json and launch.sh to output_dir."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    cfg_path = out / "vllm_config.json"
    cfg_path.write_text(json.dumps(config, indent=2))

    script = generate_launch_script(config)
    sh_path = out / "launch_vllm.sh"
    sh_path.write_text(script)
    sh_path.chmod(0o755)

    logger.info("vLLM config written to %s", out)
    return {"config": str(cfg_path), "script": str(sh_path)}
