"""Production Pack — one-click deployment bundle generator.

Produces a ZIP containing everything needed to deploy the distilled model:
  - Model weights (chosen export formats)
  - vLLM launch script + server config
  - llama.cpp server config
  - Docker Compose manifest
  - Inference example (Python + curl)
  - Export manifest (JSON summary)

Usage in the UI:
    from distill.ui.components.production_pack import ProductionPack
    pack = ProductionPack()
    pack.render()
"""
from __future__ import annotations

import json
import logging
import tempfile
import zipfile
from pathlib import Path
from typing import Any

import gradio as gr

logger = logging.getLogger(__name__)


# ── Pack builder ───────────────────────────────────────────────────────────────

def build_pack(
    model_path: str,
    export_results: dict[str, Any],
    output_dir: str,
    system_prompt: str = "You are a helpful assistant.",
    vllm_port: int = 8000,
    llama_port: int = 8080,
) -> str:
    """Build a production deployment ZIP and return its path.

    Args:
        model_path:     Path to the trained model checkpoint.
        export_results: Dict of format_key → result dict from export_matrix.
        output_dir:     Where to write the ZIP.
        system_prompt:  Default system prompt for the served model.
        vllm_port:      Port for the vLLM server config.
        llama_port:     Port for the llama.cpp server config.

    Returns:
        Path to the produced ZIP file.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    model_name = Path(model_path).name or "distilled_model"

    files: dict[str, str] = {}

    # ── vLLM launch script ─────────────────────────────────────────────────
    gguf_path = _find_artifact(export_results, "safetensors", model_path)
    files["deploy/launch_vllm.sh"] = _vllm_script(gguf_path, vllm_port, system_prompt)
    files["deploy/vllm_config.json"] = json.dumps(_vllm_config(gguf_path, vllm_port), indent=2)

    # ── llama.cpp server script ────────────────────────────────────────────
    gguf_artifact = _find_artifact(export_results, "gguf", model_path)
    files["deploy/launch_llamacpp.sh"] = _llamacpp_script(gguf_artifact, llama_port, system_prompt)

    # ── Docker Compose ────────────────────────────────────────────────────
    files["deploy/docker-compose.yml"] = _docker_compose(
        model_name, gguf_path, vllm_port, llama_port
    )

    # ── Inference example ──────────────────────────────────────────────────
    files["examples/inference_example.py"] = _inference_example(vllm_port, system_prompt)
    files["examples/curl_example.sh"]      = _curl_example(vllm_port, system_prompt)

    # ── Export manifest ────────────────────────────────────────────────────
    manifest = _build_manifest_json(model_path, export_results, system_prompt)
    files["manifest.json"] = json.dumps(manifest, indent=2)

    # ── README ────────────────────────────────────────────────────────────
    files["README.md"] = _readme(model_name, manifest, vllm_port, llama_port)

    # ── ZIP it ────────────────────────────────────────────────────────────
    zip_path = out / f"{model_name}_production_pack.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname, content in files.items():
            zf.writestr(fname, content)

    logger.info("Production pack: %s (%d files)", zip_path, len(files))
    return str(zip_path)


# ── File content generators ────────────────────────────────────────────────────

def _vllm_script(model_path: str, port: int, system_prompt: str) -> str:
    return f"""#!/usr/bin/env bash
# Auto-generated by Wow Sausage Maker — vLLM launch script
set -euo pipefail

MODEL="{model_path}"
PORT={port}
SYSTEM_PROMPT="{system_prompt}"

python -m vllm.entrypoints.openai.api_server \\
    --model "$MODEL" \\
    --host 0.0.0.0 \\
    --port "$PORT" \\
    --dtype auto \\
    --max-model-len 4096 \\
    --gpu-memory-utilization 0.90 \\
    --trust-remote-code

echo "vLLM serving at http://localhost:$PORT"
"""


def _vllm_config(model_path: str, port: int) -> dict:
    return {
        "model": model_path, "host": "0.0.0.0", "port": port,
        "dtype": "auto", "max_model_len": 4096,
        "gpu_memory_utilization": 0.90, "trust_remote_code": True,
    }


def _llamacpp_script(gguf_path: str, port: int, system_prompt: str) -> str:
    llama_bin = "/Users/Shared/llama/llama-server"
    return f"""#!/usr/bin/env bash
# Auto-generated by Wow Sausage Maker — llama.cpp server
set -euo pipefail

LLAMA_SERVER="{llama_bin}"
MODEL="{gguf_path}"
PORT={port}

"$LLAMA_SERVER" \\
    --model "$MODEL" \\
    --host 0.0.0.0 \\
    --port "$PORT" \\
    --ctx-size 4096 \\
    --threads "$(sysctl -n hw.ncpu)" \\
    --system-prompt "{system_prompt}"

echo "llama.cpp serving at http://localhost:$PORT"
"""


def _docker_compose(name: str, model_path: str, vllm_port: int, llama_port: int) -> str:
    return f"""version: "3.9"
# Auto-generated by Wow Sausage Maker
services:
  {name}-vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    volumes:
      - {model_path}:/model:ro
    command: --model /model --host 0.0.0.0 --port {vllm_port} --dtype auto
    ports:
      - "{vllm_port}:{vllm_port}"
    profiles: ["gpu"]

  {name}-llamacpp:
    image: ghcr.io/ggerganov/llama.cpp:server
    volumes:
      - {model_path}:/models:ro
    command: --model /models/model.gguf --host 0.0.0.0 --port {llama_port}
    ports:
      - "{llama_port}:{llama_port}"
    profiles: ["cpu"]
"""


def _inference_example(port: int, system_prompt: str) -> str:
    return f'''#!/usr/bin/env python3
"""Inference example — OpenAI-compatible API."""
from openai import OpenAI

client = OpenAI(base_url="http://localhost:{port}/v1", api_key="none")

response = client.chat.completions.create(
    model="distilled",
    messages=[
        {{"role": "system",  "content": "{system_prompt}"}},
        {{"role": "user",    "content": "What is knowledge distillation?"}},
    ],
    max_tokens=256,
)
print(response.choices[0].message.content)
'''


def _curl_example(port: int, system_prompt: str) -> str:
    return f"""#!/usr/bin/env bash
# Quick curl test against the OpenAI-compatible endpoint
curl -s http://localhost:{port}/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -d '{{
    "model": "distilled",
    "messages": [
      {{"role":"system","content":"{system_prompt}"}},
      {{"role":"user","content":"Hello! What can you do?"}}
    ],
    "max_tokens": 128
  }}' | python3 -m json.tool
"""


def _build_manifest_json(model_path: str, results: dict, system_prompt: str) -> dict:
    import datetime
    return {
        "generated_by": "distill.ui.components.production_pack",
        "created_at":   datetime.datetime.now().isoformat(timespec="seconds"),
        "model_path":   model_path,
        "system_prompt": system_prompt,
        "exports": {
            k: {"output_path": v.get("output_path", ""), "success": v.get("success", False),
                "size_mb": v.get("size_mb", 0)}
            for k, v in results.items()
        },
    }


def _readme(name: str, manifest: dict, vllm_port: int, llama_port: int) -> str:
    n_ok = sum(1 for v in manifest["exports"].values() if v["success"])
    return f"""# {name} — Production Deployment Pack

Generated by **Wow Sausage Maker** LLM Distillation Control Center.

## Included Files

| File | Purpose |
|---|---|
| `deploy/launch_vllm.sh` | vLLM OpenAI-compatible server (GPU) |
| `deploy/launch_llamacpp.sh` | llama.cpp server (CPU / Apple Silicon) |
| `deploy/docker-compose.yml` | Docker Compose for GPU and CPU profiles |
| `deploy/vllm_config.json` | vLLM server configuration |
| `examples/inference_example.py` | Python inference example |
| `examples/curl_example.sh` | curl API test |
| `manifest.json` | Export manifest ({n_ok} format(s) exported) |

## Quick Start

**GPU (vLLM):**
```bash
bash deploy/launch_vllm.sh
python examples/inference_example.py
```

**CPU / Apple Silicon (llama.cpp):**
```bash
bash deploy/launch_llamacpp.sh
bash examples/curl_example.sh
```

**Docker:**
```bash
docker compose --profile gpu up    # NVIDIA GPU
docker compose --profile cpu up    # CPU / Apple Silicon
```

API endpoint: `http://localhost:{vllm_port}/v1` (vLLM) or `http://localhost:{llama_port}` (llama.cpp)
"""


def _find_artifact(results: dict, format_key: str, fallback: str) -> str:
    if format_key in results:
        p = results[format_key].get("output_path", "")
        if p:
            return p
    return fallback


# ── Gradio component ───────────────────────────────────────────────────────────

class ProductionPack:
    """Gradio panel for generating and downloading a production deployment pack."""

    def render(self) -> None:
        """Render inside the current gr.Blocks context."""
        gr.Markdown("### 📦 Production Deployment Pack")
        gr.Markdown(
            "Bundle all export formats + server configs + Docker manifest "
            "into a single ZIP for immediate deployment."
        )

        with gr.Row():
            model_path = gr.Textbox(
                label="Model Checkpoint Path",
                placeholder="/Users/Shared/llama/models/my-distilled-model",
                scale=3,
            )
            scan_btn = gr.Button("🔍 Scan", variant="secondary", scale=0)

        system_prompt = gr.Textbox(
            label="System Prompt", lines=2,
            value="You are a helpful assistant.",
        )
        with gr.Row():
            vllm_port  = gr.Number(value=8000, label="vLLM Port",    precision=0)
            llama_port = gr.Number(value=8080, label="llama.cpp Port", precision=0)

        pack_btn  = gr.Button("📦 Build Production Pack", variant="primary")
        status_md = gr.Markdown("")
        download  = gr.File(label="Download Pack", visible=False)

        def do_scan():
            try:
                from distill.ui.tabs.swarm_utils import detect_artifacts_summary
                _, paths = detect_artifacts_summary()
                return gr.update(value=paths[0] if paths else "")
            except Exception:
                return gr.update()

        def do_build(path, prompt, vp, lp):
            if not path:
                return "❌ No model path specified.", gr.update(visible=False)
            try:
                import tempfile
                tmp_dir = tempfile.mkdtemp(prefix="distill_pack_")
                zip_path = build_pack(
                    model_path=path, export_results={},
                    output_dir=tmp_dir, system_prompt=prompt,
                    vllm_port=int(vp), llama_port=int(lp),
                )
                return (
                    f"✅ Pack built: `{Path(zip_path).name}`",
                    gr.update(value=zip_path, visible=True),
                )
            except Exception as exc:
                logger.error("Production pack failed: %s", exc)
                return f"❌ {exc}", gr.update(visible=False)

        scan_btn.click(fn=do_scan, outputs=model_path)
        pack_btn.click(
            fn=do_build,
            inputs=[model_path, system_prompt, vllm_port, llama_port],
            outputs=[status_md, download],
        )
